language: ruby
rvm:
  - 2.1.2
addons:
  code_climate:
    repo_token: df721421e861d472e8fa6c1701e6e782b620d9dab9617523409875c39fca26a6
env:
  - DB=mysql
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake
before_script:
  - cp config/database.travis.yml config/database.yml
  - mysql -e 'create database metroplex_test'