# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bd94c1796566a74bd4a694fd97ae61db255b0d65d0188de9bf2a6628aa9ee4614fde23fdb9445187ea7af3bf26baae7ad575dc36e7acbef52e893c654f2e3b08

test:
  secret_key_base: c4051a5218e0550aec48151293e97349084f2b15c494927cd8d8603a07942179d05a002df085ee5ced98aeccf09feb2d977a52c3ccd2f0c230fd93b48c7bf8ae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
